# Generated by Django 4.2.4 on 2023-08-17 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="as_menu",
        ),
        migrations.AddField(
            model_name="product",
            name="as_menu",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="menu.menu"
            ),
        ),
    ]
