# Generated by Django 4.2.4 on 2023-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_as_menu_product_as_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
