# Generated by Django 4.2.4 on 2023-08-17 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="collection",
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
    ]
