# Generated by Django 4.2.4 on 2023-08-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_remove_product_collection_delete_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
