# Generated by Django 4.2.4 on 2023-08-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("dob", models.DateField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=False)),
                ("isVerified", models.BooleanField(default=False)),
                ("verified_code", models.CharField(max_length=10)),
                ("expired", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
